commit: "cbd90316ebc857b1e4ae72adeec13b84f6c9894c"
buildDate: "20230305080124"
image: "011169381224.dkr.ecr.ap-southeast-1.amazonaws.com/springboot-template"

namespace: test

jvm:
  options:
    -Xlog:gc,gc+heap,gc+metaspace

spring:
  profiles: test

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 120
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 120
  periodSeconds: 10

replicas: 1

resources:
  requests:
    memory: "512Mi"
  limits:
    memory: "512Mi"

terminationGracePeriodSeconds: 30
