commit: "9000300a7555da9c8334183ef7426ea4449d3e8e"
buildDate: "20230308062650"
image: "011169381224.dkr.ecr.ap-southeast-1.amazonaws.com/springboot-template"

namespace: default

jvm:
  options:
    -Xlog:gc,gc+heap,gc+metaspace

spring:
  profiles: dev

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 5

replicas: 1

resources:
  requests:
    memory: "512Mi"
  limits:
    memory: "512Mi"

terminationGracePeriodSeconds: 30
